/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var m = Object.defineProperty;
var y = Object.getOwnPropertyDescriptor;
var f = Object.getOwnPropertyNames;
var d = Object.prototype.hasOwnProperty;
var g = (n, i) => {
		for (var e in i) m(n, e, { get: i[e], enumerable: !0 });
	},
	v = (n, i, e, t) => {
		if ((i && typeof i == "object") || typeof i == "function")
			for (let s of f(i))
				!d.call(n, s) &&
					s !== e &&
					m(n, s, {
						get: () => i[s],
						enumerable: !(t = y(i, s)) || t.enumerable,
					});
		return n;
	};
var T = (n) => v(m({}, "__esModule", { value: !0 }), n);
var E = {};
g(E, { default: () => c });
module.exports = T(E);
var a = require("obsidian"),
	r = "zen-zone-view",
	w = "mPZkdNFkNps",
	p = class {
		constructor(i, e) {
			(this.iframe = i.createEl("iframe")),
				(this.iframe.width = "0"),
				(this.iframe.height = "0"),
				(this.iframe.src = `https://www.youtube.com/embed/${e}?enablejsapi=1&controls=0&loop=1&playlist=${e}`),
				(this.iframe.allow = "autoplay"),
				(this.iframe.style.display = "none");
		}
		postCommand(i, e = []) {
			this.iframe.contentWindow &&
				this.iframe.contentWindow.postMessage(
					JSON.stringify({ event: "command", func: i, args: e }),
					"*"
				);
		}
		play() {
			this.postCommand("playVideo");
		}
		pause() {
			this.postCommand("pauseVideo");
		}
		setVolume(i) {
			this.postCommand("setVolume", [i * 100]);
		}
	},
	h = class extends a.ItemView {
		constructor(e, t) {
			super(e);
			this.timerInterval = null;
			this.timeLeft = 25 * 60;
			this.isRunning = !1;
			this.ytPlayer = null;
			this.plugin = t;
		}
		getViewType() {
			return r;
		}
		getDisplayText() {
			return "Zen Zone (YouTube)";
		}
		getIcon() {
			return "youtube";
		}
		async onOpen() {
			let e = this.containerEl.children[1];
			e.empty(),
				e.createEl("h2", { text: "\u{1F9D8} Zen Zone" }),
				(this.ytPlayer = new p(e, w));
			let t = e.createDiv({ cls: "zen-timer" });
			t.setText(this.formatTime(this.timeLeft));
			let l = e
				.createDiv({ cls: "zen-controls" })
				.createEl("button", { text: "Start Focus" });
			(l.onclick = () => this.toggleTimer(l, t)),
				e.createEl("h4", { text: "\u{1F3A7} YouTube Mixer" }),
				this.createSlider(e, "\u{1F50A} Volume", (o) => {
					this.ytPlayer &&
						(this.ytPlayer.setVolume(o),
						o > 0 && !this.isRunning && this.ytPlayer.play());
				}),
				e.createDiv({
					text: "\u203B\u518D\u751F\u958B\u59CB\u6642\u306BYouTube\u5E83\u544A\u304C\u6D41\u308C\u308B\u5834\u5408\u304C\u3042\u308A\u307E\u3059\u3002",
					cls: "zen-note",
					attr: {
						style: "font-size: 0.8em; color: gray; margin-top: 10px;",
					},
				});
		}
		createSlider(e, t, s) {
			let l = e.createDiv({ cls: "zen-slider-wrapper" });
			l.createSpan({ text: t });
			let o = l.createEl("input", {
				type: "range",
				attr: { min: 0, max: 1, step: 0.1, value: 0 },
			});
			o.oninput = (u) => s(parseFloat(u.target.value));
		}
		toggleTimer(e, t) {
			this.isRunning
				? (this.stopTimer(),
				  e.setText("Start Focus"),
				  this.plugin.exitZenMode(),
				  this.ytPlayer && this.ytPlayer.pause())
				: ((this.isRunning = !0),
				  e.setText("Stop"),
				  this.plugin.enterZenMode(),
				  this.ytPlayer && this.ytPlayer.play(),
				  (this.timerInterval = window.setInterval(() => {
						this.timeLeft--,
							t.setText(this.formatTime(this.timeLeft)),
							this.timeLeft <= 0 && this.completeSession(e);
				  }, 1e3)));
		}
		stopTimer() {
			(this.isRunning = !1),
				this.timerInterval &&
					(clearInterval(this.timerInterval),
					(this.timerInterval = null));
		}
		completeSession(e) {
			this.stopTimer(),
				this.plugin.exitZenMode(),
				this.ytPlayer && this.ytPlayer.pause(),
				e.setText("Start Focus"),
				(this.timeLeft = 25 * 60),
				this.plugin.showBreakOverlay();
		}
		formatTime(e) {
			let t = Math.floor(e / 60),
				s = e % 60;
			return `${t}:${s.toString().padStart(2, "0")}`;
		}
		async onClose() {
			this.ytPlayer && this.ytPlayer.pause();
		}
	},
	c = class extends a.Plugin {
		constructor() {
			super(...arguments);
			this.overlayEl = null;
		}
		async onload() {
			this.registerView(r, (e) => new h(e, this)),
				this.addRibbonIcon("youtube", "Open Zen Zone (YT)", () => {
					this.activateView();
				}),
				this.addCommand({
					id: "open-zen-zone",
					name: "Open Zen Zone Panel",
					callback: () => this.activateView(),
				});
		}
		async activateView() {
			let { workspace: e } = this.app,
				t = null,
				s = e.getLeavesOfType(r);
			s.length > 0
				? (t = s[0])
				: ((t = e.getRightLeaf(!1)),
				  t && (await t.setViewState({ type: r, active: !0 }))),
				t && e.revealLeaf(t);
		}
		enterZenMode() {
			document.body.classList.add("zen-mode-active"),
				this.app.workspace.leftSplit &&
					this.app.workspace.leftSplit.collapse(),
				this.app.workspace.rightSplit &&
					this.app.workspace.rightSplit.collapse(),
				new a.Notice("\u{1F9D8} Zen Mode Activated (with YouTube)");
		}
		exitZenMode() {
			document.body.classList.remove("zen-mode-active"),
				new a.Notice("Zen Mode Deactivated");
		}
		showBreakOverlay() {
			this.overlayEl = document.body.createDiv({
				cls: "zen-break-overlay",
			});
			let e = this.overlayEl.createDiv({ cls: "zen-break-content" });
			e.createEl("h1", { text: "Time to Breathe" }),
				e.createEl("p", {
					text: "\u304A\u75B2\u308C\u69D8\u3067\u3057\u305F\u3002YouTube\u3082\u505C\u6B62\u3057\u307E\u3057\u305F\u3002",
				});
			let t = e.createEl("button", {
				text: "\u4F11\u61A9\u3092\u7D42\u3048\u308B",
			});
			t.onclick = () => {
				this.overlayEl &&
					(this.overlayEl.remove(), (this.overlayEl = null));
			};
		}
	};
